(function(b){function d(a){a.startSymbol("{[");a.endSymbol("]}")}function c(a,c,d){function e(l){13===l.which&&a.submitTranslit()}function p(l){a.hideEULA?(a.loadDatasetInfo(),a.showLanguageDialog(l,a,c)):a.showEulaDialog(l,a,c)}function q(a,b,c){c.show({parent:h,targetEvent:a,templateUrl:"warning.html",scope:b,preserveScope:!0,locals:{},onShowing:b.loadDatasetInfo(),controller:b.eulaDialogController})}function r(a,b){a.quitWarn=function(){k("hideEULA",a.hideEULA);b.hide()};a.selectLang=function(c){k("hideEULA",
a.hideEULA);b.hide();a.showLanguageDialog(c,a,b)}}function t(a,b,c){c.show({parent:h,targetEvent:a,templateUrl:"lang.html",scope:b,preserveScope:!0,locals:{},controller:b.langDialogController})}function u(a,b){a.quitLang=function(){b.hide();m(a.selectedLanguage)};a.beginTask=function(c){b.hide();m(a.selectedLanguage);a.loadTask();n("guideShown")?a.showTaskDialog(c,a,b):(k("guideShown",!0),a.showGuideDialog(a,b))}}function x(a,b,c){c.show({parent:h,targetEvent:a,templateUrl:"task.html",scope:b,preserveScope:!0,
locals:{},ononComplete:b.focusTranslit(),controller:b.taskDialogController})}function y(a,b){a.nextTask=function(){a.submitTranslit()};a.completeTask=function(){b.hide();a.showCompleteDialog(a,b)};a.showGuide=function(){a.showGuideDialog(a,b)}}function z(a,b){b.show({parent:h,templateUrl:"complete.html",scope:a,preserveScope:!0,locals:{},onShowing:a.loadTask(),controller:a.completeDialogController})}function A(a,b){a.quitApp=function(){b.hide()};a.reloadTask=function(c){a.submitCountInTask=0;b.hide();
a.showTaskDialog(c,a,b)}}function B(a,b){b.show({parent:h,templateUrl:"guide.html",scope:a,preserveScope:!0,locals:{},controller:a.guideDialogController})}function C(a,b){a.restoreTask=function(c){b.hide();a.showTaskDialog(c,a,b);a.focusTranslit()}}var h=b.element(document.body);a.eulaDialogController=r;a.langDialogController=u;a.taskDialogController=y;a.completeDialogController=A;a.guideDialogController=C;a.launchApp=p;a.getDisplayLanguage=function(c){if(!c||0===c.length||"und"===c)return c;var d=
a.indexedDatasets[v(c)];return d&&b.isArray(d)&&0!==d.length?d[0].language_display:c};a.updateTaskProgress=function(){return 0===a.targetWords.length?0:100*a.curTargetIndex/a.targetWords.length};a.validateTranslit=function(){a.invalidTranslit=!a.curTranslit&&0<a.curTranslit.length};a.keypressInTranslit=e;a.showEulaDialog=q;a.showLanguageDialog=t;a.showTaskDialog=x;a.showCompleteDialog=z;a.showGuideDialog=B;a.focusTranslit=function(){a.translitTextArea=document.getElementById("translitInput");a.translitTextArea&&
a.translitTextArea.focus()};a.loadDatasetInfo=function(){d(w("","",0,0)).then(function(c){a:{if((c=D(c.data))&&"data_set_info"in c&&(c=c.data_set_info,angular.isArray(c)&&0<c.length))break a;c=[]}if(b.isArray(c)&&0!==c.length){console.log("Datasets loaded successfully.");for(var d=c,e=0;e<d.length;e++)E(d[e]);d={};if(angular.isArray(c)&&0!==c.length)for(e=0;e<c.length;e++){var f=v(c[e].language);f&&(f in d||(d[f]=[]),d[f].push(c[e]))}a.indexedDatasets=d;c=a.indexedDatasets;var d=[],g;for(g in c)d.push(c[g][0].language);
a.languages=d;a.selectedLanguage&&0<a.languages.indexOf(a.selectedLanguage)?console.log("Preferred language:"+a.selectedLanguage):a.selectedLanguage=a.languages[0]}else console.log("Datasets are empty.")},function(){console.log("Failed to load dataset summary.")})};a.loadTask=function(){a.resetTask();a.curDataset=F(a.indexedDatasets,a.selectedLanguage);if("translit_example"in a.curDataset){var c=a.curDataset.translit_example;b.isArray(c)&&0<c.length&&(a.exampleTranslit=c[0])}c=a.curDataset.start_pos+
a.curDataset.finished_count;c>=a.curDataset.total_count&&(c-=a.curDataset.total_count);d(w(a.selectedLanguage,a.curDataset.name,c,10)).then(function(b){"target"in b.data&&(a.targetWords=b.data.target);0<a.targetWords.length?(a.curTargetIndex=0,a.curTargetWord=a.targetWords[0],a.curTranslit="",a.dataNotReady=!1):console.log("No target word loaded.")},function(a){console.log("Failed to load target words:"+a.statusText)})};a.submitTranslit=function(){a.curTargetIndex+=1;a.curDataset.finished_count+=
1;a.curTranslit&&0<a.curTranslit.length&&(a.submitCountInTask+=1,a.submitCountInLaunch+=1,a.submitCountOverall+=1,G(a.submitCountOverall),d(H(a.curTargetWord,a.selectedLanguage,a.curTranslit)).then(function(a){a=D(a.data);angular.isArray(a)},function(a){console.log("Submit failed:"+a.statusText)}));E(a.curDataset);a.curTargetIndex>=a.targetWords.length?(a.resetTask(),a.completeTask()):(a.curTargetWord=a.targetWords[a.curTargetIndex],a.curTranslit="",a.invalidTranslit=!0,a.focusTranslit())};a.resetTask=
function(){a.dataNotReady=!0;a.invalidTranslit=!0;a.curTargetIndex=0;a.curTargetWord="";a.curTranslit="";a.targetWords=[]};a.indexedDatasets={};a.hideEULA=n("hideEULA");a.languages=[];a.selectedLanguage=angular.isString("selectedLanguage")?window.localStorage.getItem("selectedLanguage"):"";a.curTargetWord="";a.curTranslit="";a.dataNotReady=!0;a.invalidTranslit=!0;a.submitCountInTask=0;a.submitCountInLaunch=0;a.submitCountOverall=I();a.exampleTranslit={source:"namaste",target:"\u0928\u092e\u0938\u094d\u0924\u0947"};
a.curDataset={};a.targetWords=[];a.curTargetIndex=0;a.translitTextArea=null;e.$inject=["$event"];p.$inject=["$event"];q.$inject=["$event","$scope","$mdDialog"];r.$inject=["$scope","$mdDialog"];t.$inject=["$event","$scope","$mdDialog"];u.$inject=["$scope","$mdDialog"];x.$inject=["$event","$scope","$mdDialog"];y.$inject=["$scope","$mdDialog"];z.$inject=["$scope","$mdDialog"];A.$inject=["$scope","$mdDialog"];B.$inject=["$scope","$mdDialog"];C.$inject=["$scope","$mdDialog"]}d.$inject=["$interpolateProvider"];
b.module("ugcApp",["ngMaterial"],d).controller("ugcCtrl",["$scope","$mdDialog","$http",c]);c.$inject=["$scope","$mdDialog","$http"]})(angular,null);function v(b){return angular.isString(b)&&0<b.length?(b=angular.lowercase(b.trim()),b.replace("-","_"),b):""}
function H(b,d,c){var a={method:"POST",url:"https://inputtools.google.com/inputtools/ugc/submit",data:"",headers:{"Content-Type":"application/json"},withCredentials:!0},f={};f.target=b;f.target_lang=d;angular.isArray(c)?f.source=c:angular.isString(c)?(f.source=[],f.source.push(c)):console.log("bad data for submit");f.source_lang="en";a.data=angular.toJson(f);return a}
function w(b,d,c,a){var f={method:"POST",url:"https://inputtools.google.com/inputtools/ugc/fetch",data:"",headers:{"Content-Type":"application/json"},withCredentials:!0},g={};angular.isString(b)&&0<b.length&&(g.language=b,angular.isString(d)&&0<d.length&&(g.data_set_name=d,0<c||0<a))&&(g.range={},g.range.pos=c,g.range.count=a);f.data=angular.toJson(g);return f}function D(b){var d={};angular.isString(b)&&0<b.length?d=angular.fromJson(b):angular.isObject(b)&&(d=b);return angular.isObject(d)?d:{}}
function F(b,d){var c={};if(!angular.isObject(b)||!angular.isString(d))return console.log("Wrong arg for pick task"),c;var a=v(d),f=b[a];if(!angular.isArray(f)||0===f.length)return console.log("No dataset picked for language."),c;for(var g=0;g<f.length;g++){var e;e=f[g].name;e=v(a)+e;e=J(e);if((e=angular.isObject(e)?e:null)&&angular.isObject(e)&&"total_count"in e&&"start_pos"in e)e.finished_count<e.total_count&&(c=e);else{c=f[g];c.start_pos=Math.floor(Math.random()*c.total_count);c.finished_count=
0;E(c);break}}return c}
function E(b){if(b&&angular.isObject(b)&&"language"in b&&"name"in b){var d=v(b.language)+b.name,c=J(d),a=!1;c&&angular.isObject(c)&&"name"in c?("finished_count"in b?(c.finished_count=b.finished_count,a=!0):"finished_count"in b||(c.finished_count=0,a=!0),b.count!==c.count&&(c.count=b.count,a=!0)):(a=!0,c=b,"start_pos"in c||(c.start_pos=Math.floor(Math.random()*c.total_count)),c.finished_count=0);a&&(b=c,d&&angular.isString(d)&&0<d.length&&window.localStorage.setItem(d,angular.toJson(b,!1)))}}
function J(b){return b&&angular.isString(b)&&0<b.length&&(b=window.localStorage.getItem(b))?angular.fromJson(b):{}}function m(b){angular.isString("selectedLanguage")&&window.localStorage.setItem("selectedLanguage",b)}function G(b){angular.isString("totalSubmission")&&window.localStorage.setItem("totalSubmission",b.toString())}function I(){var b=0;angular.isString("totalSubmission")&&(b=parseInt(window.localStorage.getItem("totalSubmission"),10),isNaN(b)&&(b=0));return b}
function k(b,d){b&&angular.isString(b)&&0<b.length&&window.localStorage.setItem(b,d?"yes":"no")}function n(b){var d=!1;b&&angular.isString(b)&&0<b.length&&"yes"===window.localStorage.getItem(b)&&(d=!0);return d};
